# serene v5.2.1
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================

base_url = "https://lovelindhoni.github.io"
title = "Lovelin Dhoni JB | personal site"
description = "Lovelin Dhoni JB is a cs undergraduate in chennai institute of technology."
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false 
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
lazy_async_image = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false },
  { name = "works", path = "/works", is_external = false },
  { name = "shelf", path = "/shelf", is_external = false }
]
blog_section_path = "/posts"

back_link_text = "Back"
force_theme = "light"

footer_copyright = "© 2025 Lovelin Dhoni JB"
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = true
reaction_align = "left"
reaction_endpoint = "https://lovelin-blog-reaction-server.jblovelindhoni.workers.dev"
